# The URL the site will be built for
base_url = "https://7a6163.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anatole-zola"
title = "Dev Note"
description = "Aim for the impossible"
default_language = "en"

generate_rss = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"
date_format = "%d-%m-%Y"

[extra.social]
github = "7a6163"
twitter = "7a6163"

[extra.comment.utterances]
repo = "7a6163/7a6163.github.io"
issue_term = "pathname"
theme = "github-light"
